trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunTerraform
  displayName: 'Run Terraform'
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      inputs:
        terraformVersion: '0.14.9'
        terraformCheckLatest: false

    - task: AzureCLI@2
      inputs:
        azureSubscription: '<Name of your Azure service connection>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version
          az login --tenant 08a1a72f-fecd-4dae-8cec-471a2fb7c2f1
    - script: |
        terraform init
        terraform validate
        terraform plan -out=tfplan
      displayName: 'Terraform Init & Plan'

    - script: terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
