trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  displayName: 'Run Terraform'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
  - task: TerraformTaskV4@4
    inputs:
     provider: 'azurerm'
     command: 'apply'

  - script: |
      terraform init
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
